---
name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */7 * *'
  push:
    branches: ["master"]
    paths-ignore:
      - '.github/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout repository code
      # https://github.com/actions/checkout
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4.1.1

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        id: login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest

      # Build Docker image with Buildx and use cache
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Test with dive
      - name: Test with Dive
        id: dive
        env:
          IMAGE_NAME: ${{ steps.meta.outputs.tags }}
          CI: true
        run: |
          wget -q https://github.com/wagoodman/dive/releases/download/v0.11.0/dive_0.11.0_linux_amd64.tar.gz
          tar -xvf dive_0.11.0_linux_amd64.tar.gz
          ./dive $IMAGE_NAME

      # Test application
      - name: Test Application
        id: app
        env:
          IMAGE_NAME: ${{ steps.meta.outputs.tags }}
        run: |
          set +e
          timeout -k 5 60 docker run "$IMAGE_NAME"
          RC=$?
          if [ "$RC" = "137" ] || [ "$RC" = "0" ];
          then
            exit 0
          else
            exit $RC
          fi

      # Build and push Docker image with Buildx and use cache
      # https://github.com/docker/build-push-action
      - name: Push Docker image
        id: push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max